version: '3.8'

services:
  app:
    build:
      context: .
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - symfony
    command: >
      sh -c "
      composer install --no-interaction --no-dev --optimize-autoloader &&
      php-fpm
      "

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: postgres:13
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - symfony

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - symfony

  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - symfony

volumes:
  db-data:
  pgadmin-data:

networks:
  symfony:
    driver: bridge
